  CREATE TABLE "ANNA"."CONTACTS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"MOBILE" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  CREATE TABLE "ANNA"."USER_DETAILS" 
   (	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
select * from USER_DETAILS;
create table USER_DETAILS(username VARCHAR2(255), password VARCHAR2(255));
insert into USER_DETAILS(username, password) values ('anna','anna');
create table REGISTRATION(id VARCHAR2(255),firstname VARCHAR2(255), lastname VARCHAR2(255), address VARCHAR2(255), age VARCHAR2(255));
insert into REGISTRATION(firstname, lastname, address, age) values ('anna','anna','street','29568');
COMMIT WORK;

alter table REGISTRATION add (id VARCHAR2(255));
SELECT * FROM REGISTRATION;

INSERT INTO "ANNA"."CONTACTS" (ID, NAME, ADDRESS, GENDER, EMAIL, MOBILE, PHONE) VALUES ('11', 'aa', 's', 'df', 'a', '999999', '545454');
SELECT   * FROM   CONTACTS;
ALTER TABLE CONTACTS  MODIFY (ID VARCHAR2(20) );
DROP TABLE CONTACTS;
commit;